/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cifrado.viggener;

import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author waldo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Vigikawaii vigi= new Vigikawaii();
    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_msj = new javax.swing.JTextArea();
        btn_des = new javax.swing.JButton();
        btn_cifra = new javax.swing.JButton();
        btn_clean = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_p = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("CIFRADO VIGGENER DE LA MUERTE KAWAII <3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, 38));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 102));
        jLabel3.setText("Ingrese el mensaje a cifrar asi como la clave del cifrado UwU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 430, 60));

        txt_key.setBackground(new java.awt.Color(1, 27, 44));
        txt_key.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        txt_key.setForeground(new java.awt.Color(255, 255, 255));
        txt_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keyActionPerformed(evt);
            }
        });
        getContentPane().add(txt_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, 20));

        txt_msj.setBackground(new java.awt.Color(1, 27, 44));
        txt_msj.setColumns(20);
        txt_msj.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        txt_msj.setForeground(new java.awt.Color(255, 255, 255));
        txt_msj.setRows(5);
        jScrollPane1.setViewportView(txt_msj);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 270, 170));

        btn_des.setBackground(new java.awt.Color(1, 27, 44));
        btn_des.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btn_des.setForeground(new java.awt.Color(255, 255, 255));
        btn_des.setText("DESCIFRAR");
        btn_des.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desActionPerformed(evt);
            }
        });
        getContentPane().add(btn_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 170, 70));

        btn_cifra.setBackground(new java.awt.Color(1, 27, 44));
        btn_cifra.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btn_cifra.setForeground(new java.awt.Color(255, 255, 255));
        btn_cifra.setText("CIFRAR");
        btn_cifra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifraActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cifra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, 70));

        btn_clean.setBackground(new java.awt.Color(1, 27, 44));
        btn_clean.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btn_clean.setForeground(new java.awt.Color(255, 255, 255));
        btn_clean.setText("BORRAR");
        btn_clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 170, 70));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 102));
        jLabel4.setText("CLAVE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        txt_p.setBackground(new java.awt.Color(255, 51, 102));
        txt_p.setForeground(new java.awt.Color(0, 0, 204));
        txt_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        getContentPane().add(txt_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desActionPerformed
        // TODO add your handling code here:
        if (txt_key.getText().length() < 1 || txt_msj.getText().length() < 1) {
            JOptionPane.showMessageDialog(null,"Inserte una clave y un mensaje UwU");
        }else{
            if (txt_key.getText().length() > txt_msj.getText().length()) {
            
            JOptionPane.showMessageDialog(null,"Para desencriptar el mesaje la clave debe ser menor que el mismo mensaje UwU");
            
        }else{

            txt_msj.setText(vigi.desencriptarTextoCifrado(txt_msj.getText(), txt_key.getText().toUpperCase()));
 
        
        }
        }
        
        
        
    }//GEN-LAST:event_btn_desActionPerformed

    private void txt_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keyActionPerformed

    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        // TODO add your handling code here:
        txt_msj.setText(" ");
        txt_key.setText(" ");
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void btn_cifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifraActionPerformed
        // TODO add your handling code here:

        if (txt_key.getText().length() < 1 || txt_msj.getText().length() < 1) {
            JOptionPane.showMessageDialog(null,"Inserte una clave y un mensaje UwU");
        }else{
            if (txt_key.getText().length() > txt_msj.getText().length()) {
            
            JOptionPane.showMessageDialog(null,"Para encriptar el mesaje la clave debe ser menor que el mismo mensaje UwU");
            
        }else{
            /*txt_msj.getText().toUpperCase();
            txt_key.getText().toUpperCase();*/
            
            txt_msj.setText(vigi.encriptarTextoClaro(txt_msj.getText().toUpperCase(), txt_key.getText().toUpperCase()));
        
        }
        }

        
    }//GEN-LAST:event_btn_cifraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cifra;
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextArea txt_msj;
    private javax.swing.JLabel txt_p;
    // End of variables declaration//GEN-END:variables
}
